# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Introduction to Digital Humanities
tagline: Course Website 
description: Reading materials and assignments for the course Introduction to Digital Humanities, taught at Princeton University in the Fall of 2024.
author: Wouter Haverals
baseurl: '/IntroDH-Fall2024' # the subpath of your site, e.g. /blog
url: 'https://whaverals.github.io'  # the base hostname & protocol for your site, e.g. http://example.com
logo: 'assets/favicon/class-logo.png'
favicon_ico: 'assets/favicon/class-logo.ico'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings
ga_tracking: G-GD3N1CKBGG
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# SEO Settings
seo:
  title: Introduction to Digital Humanities
  description: Course website for 'Introduction to Digital Humanities' at Princeton University by Wouter Haverals.
  keywords: Digital Humanities, Princeton University, Wouter Haverals, Introduction to Digital Humanities, Fall 2024, Course Website
  author: Wouter Haverals
  social_image: "/assets/favicon/logo-class-notext.png" 
  og:
    type: website
    url: "https://whaverals.github.io/IntroDH-Fall2024"
    title: Introduction to Digital Humanities | Princeton University
    description: Explore the resources for the 'Introduction to Digital Humanities' course at Princeton University.
    image: "/assets/favicon/class-logo.png"


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.6.1
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  #Just the Class on GitHub:
  #  - 'https://github.com/WHaverals/IntroDH-Fall2024'
#footer_content: Introduction to Digital Humanities, Princeton University, Fall 2024

callouts:
  note:
    color: purple

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

nav_order: 
  - title: Course outline
    url: /about/
  - title: Announcements
    url: /announcements/
  - title: Calendar
    url: /calendar/
  - title: Resources
    url: /resources/
  - title: Assignments
    url: /assignments/
  - title: Policies
    url: /policies/